version: '3.9'

services:
  django:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta do broker
      - "15672:15672" # Painel web de administração
    restart: always

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - django
      - rabbitmq
    restart: always

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - django
      - rabbitmq
    restart: always
