# Generated by Django 5.2.7 on 2025-10-04 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Trabalho', 'Trabalho'), ('Esportes', 'Esportes'), ('Estudos', 'Estudos'), ('Lazer', 'Lazer')], max_length=25)),
                ('init_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['init_hour'],
            },
        ),
    ]
