# Generated by Django 5.2.7 on 2025-11-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='temp_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
