# Generated by Django 5.2.7 on 2025-11-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_emailverification_temp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
